
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const PARTIAL_UPDATE_PROFILE_REQUEST = 'PARTIAL_UPDATE_PROFILE_REQUEST';
export const PARTIAL_UPDATE_PROFILE_SUCCESS = 'PARTIAL_UPDATE_PROFILE_SUCCESS';
export const PARTIAL_UPDATE_PROFILE_FAILURE = 'PARTIAL_UPDATE_PROFILE_FAILURE';