export const SUBMIT_FORM_REQUEST = "SUBMIT_USER_PROFILE_REQUEST";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_USER_PROFILE_SUCCESS";
export const SUBMIT_FORM_FAILURE = "SUBMIT_USER_PROFILE_FAILURE";

// User Profile Actions
export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

// Other user-related actions, if needed

export const UPDATE_FORM_DATA = "UPDATE_USER_PROFILE_DATA";

