spring:
  application:
    name: eureka-discovery-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    filters:
      cors:
        enabled: true
        allowedOrigins: http://localhost:3000/

logging:
  level:
    org.springframework.web:
      cors: DEBUG