export const SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_FAILURE = "SUBMIT_FORM_FAILURE";

export const FETCH_QUERIES_REQUEST = 'FETCH_QUERIES_REQUEST';
export const FETCH_QUERIES_SUCCESS = 'FETCH_QUERIES_SUCCESS';
export const FETCH_QUERIES_FAILURE = 'FETCH_QUERIES_FAILURE';

export const UPDATE_QUERY_STATUS_REQUEST = 'UPDATE_QUERY_STATUS_REQUEST';
export const UPDATE_QUERY_STATUS_SUCCESS = 'UPDATE_QUERY_STATUS_SUCCESS';
export const UPDATE_QUERY_STATUS_FAILURE = 'UPDATE_QUERY_STATUS_FAILURE';

export const UPDATE_FORM_DATA = "UPDATE_FORM_DATA";
