version: '3'
services:
  backend:
    backend:
    image: backend
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loanapp 
      SPRING_DATASOURCE_USERNAME: vinayak
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
  frontend:
    image: frontend-image
    ports:
      - "3000:3000"
      
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: loanapp
      MYSQL_USER: vinayak
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
