export const FETCH_ALL_LOANS_SUCCESS = 'FETCH_ALL_LOANS_SUCCESS';
export const FETCH_LOAN_BY_CUST_ID_SUCCESS = 'FETCH_LOAN_BY_CUST_ID_SUCCESS';
export const FETCH_LOAN_BY_STATUS_SUCCESS = 'FETCH_LOAN_BY_STATUS_SUCCESS';
export const FETCH_LOAN_BY_ID_SUCCESS = 'FETCH_LOAN_BY_ID_SUCCESS';
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS';
export const UPDATE_LOAN_STATUS_SUCCESS = 'UPDATE_LOAN_STATUS_SUCCESS';
export const NOT_FOUND_ERROR = 'NOT_FOUND_ERROR';